// L'Altra Italia Products - Based on catalog with realistic pricing and descriptions
export const lAltraItaliaProducts = [
  // BURRATA CATEGORY (18 products)
  {
    name: "Burrata de Vaca S/Cabeza",
    ProductCode: "0212000022",
    description: "Burrata artigianale pugliese di latte vaccino senza testa, dal cuore cremoso e sapore delicato. Prodotta secondo tradizione in Puglia.",
    formato: "100gr *12",
    price: 5.50,
    stock: 48,
    status: "ACTIVE",
    slug: "burrata-de-vaca-s-cabeza",
    categoryName: "Burrata",
  },
  {
    name: "Burrata de Vaca C/Cabeza",
    ProductCode: "0212000017",
    description: "Burrata tradizionale pugliese di latte vaccino con testa, dalla consistenza cremosa e gusto autentico della tradizione casearia del Sud Italia.",
    formato: "125gr *12",
    price: 6.20,
    stock: 36,
    status: "ACTIVE",
    slug: "burrata-de-vaca-c-cabeza",
    categoryName: "Burrata",
  },
  {
    name: "Burrata en Vaso",
    ProductCode: "0212000020",
    description: "Burrata artigianale conservata in vaso, perfetta per mantenere la freschezza e la cremosità. Specialità pugliese di alta qualità.",
    formato: "125gr *12",
    price: 6.80,
    stock: 24,
    status: "ACTIVE",
    slug: "burrata-en-vaso",
    categoryName: "Burrata",
  },
  {
    name: "Burrata Artigianale S/Cabeza",
    ProductCode: "0212000043",
    description: "Burrata artigianale di produzione limitata, senza testa, dal sapore intenso e cremosità eccezionale. Prodotta da maestri casari pugliesi.",
    formato: "150gr *2",
    price: 8.90,
    stock: 18,
    status: "ACTIVE",
    slug: "burrata-artigianale-s-cabeza",
    categoryName: "Burrata",
  },
  {
    name: "Burrata",
    ProductCode: "0212000029",
    description: "Burrata classica pugliese di grande formato, perfetta per condivisione. Cuore cremoso di stracciatella e panna, pasta filata esterna.",
    formato: "250gr *10",
    price: 9.50,
    stock: 30,
    status: "ACTIVE",
    slug: "burrata-classica-250gr",
    categoryName: "Burrata",
  },
  {
    name: "Burrata 200gr",
    ProductCode: "0212000018",
    description: "Burrata di formato medio, ideale per 2-3 persone. Prodotta in Puglia con latte fresco locale e tecniche tradizionali.",
    formato: "200gr",
    price: 7.80,
    stock: 42,
    status: "ACTIVE",
    slug: "burrata-200gr",
    categoryName: "Burrata",
  },
  {
    name: "Nodo in vaschetta",
    ProductCode: "0212000064",
    description: "Piccoli nodi di burrata in vaschetta, perfetti come antipasto o aperitivo. Formato mini per degustazioni raffinate.",
    formato: "50gr (5ud)",
    price: 4.20,
    stock: 60,
    status: "ACTIVE",
    slug: "nodo-in-vaschetta",
    categoryName: "Burrata",
  },
  {
    name: "Burrata Ahumada",
    ProductCode: "0212000023",
    description: "Burrata affumicata con legni aromatici, dal sapore unico e avvolgente. Specialità gourmet della tradizione pugliese moderna.",
    formato: "125gr *2",
    price: 8.50,
    stock: 20,
    status: "ACTIVE",
    slug: "burrata-ahumada",
    categoryName: "Burrata",
  },
  {
    name: "Burrata 30 Gr (6 ud)",
    ProductCode: "0212000030",
    description: "Mini burrate monoporzione, perfette per aperitivi e degustazioni. Formato piccolo ma dal grande sapore pugliese.",
    formato: "180gr *10",
    price: 6.90,
    stock: 45,
    status: "ACTIVE",
    slug: "burrata-30gr-6ud",
    categoryName: "Burrata",
  },
  {
    name: "Burrata al Gorgonzola DOP",
    ProductCode: "0212000039",
    description: "Burrata gourmet con cuore di gorgonzola DOP lombardo. Incontro perfetto tra cremosità pugliese e sapidità lombarda.",
    formato: "100Gr *12",
    price: 9.80,
    stock: 15,
    status: "ACTIVE",
    slug: "burrata-al-gorgonzola-dop",
    categoryName: "Burrata",
  },
  {
    name: "Burrata alla Nduja",
    ProductCode: "0212000040",
    description: "Burrata piccante con 'nduja calabrese, fusione di sapori del Sud Italia. Cremosità pugliese incontra il piccante calabrese.",
    formato: "200 Gr*8",
    price: 11.20,
    stock: 12,
    status: "ACTIVE",
    slug: "burrata-alla-nduja",
    categoryName: "Burrata",
  },
  {
    name: "Burrata Caprese",
    ProductCode: "0212000046",
    description: "Burrata con pomodorini e basilico, ispirata alla tradizione caprese. Freschezza campana in versione pugliese.",
    formato: "100Gr *12",
    price: 7.90,
    stock: 28,
    status: "ACTIVE",
    slug: "burrata-caprese",
    categoryName: "Burrata",
  },
  {
    name: "Burrata ai Ricci di Mare",
    ProductCode: "0212000044",
    description: "Burrata gourmet con ricci di mare, specialità di lusso che unisce la cremosità della burrata al sapore del mare pugliese.",
    formato: "100Gr *12",
    price: 15.50,
    stock: 8,
    status: "ACTIVE",
    slug: "burrata-ai-ricci-di-mare",
    categoryName: "Burrata",
  },
  {
    name: "Burrata Ahumada con Cuore di Ricotta",
    ProductCode: "0212000041",
    description: "Burrata affumicata con cuore di ricotta fresca, doppia cremosità e sapore affumicato delicato. Innovazione della tradizione.",
    formato: "100gr *16",
    price: 8.90,
    stock: 22,
    status: "ACTIVE",
    slug: "burrata-ahumada-con-cuore-ricotta",
    categoryName: "Burrata",
  },
  {
    name: "Burrata C/Trufa",
    ProductCode: "0212000019",
    description: "Burrata gourmet con tartufo, eccellenza pugliese arricchita dal pregiato tartufo italiano. Lusso e tradizione in un solo prodotto.",
    formato: "100g *12",
    price: 12.80,
    stock: 10,
    status: "ACTIVE",
    slug: "burrata-c-trufa",
    categoryName: "Burrata",
  },
  {
    name: "Burrata Anchoas del Cantábrico y pimiento",
    ProductCode: "G-ANCH-PROV",
    description: "Burrata gourmet con acciughe del Cantabrico e peperoni, fusione italo-spagnola di sapori marini e terrestri.",
    formato: "100gr *16",
    price: 13.50,
    stock: 6,
    status: "ACTIVE",
    slug: "burrata-anchoas-cantabrico-pimiento",
    categoryName: "Burrata",
  },
  {
    name: "Burrata Olive e Maggiorana",
    ProductCode: "G-OLIV-PROV",
    description: "Burrata aromatizzata con olive pugliesi e maggiorana fresca, sapori mediterranei in perfetta armonia con la cremosità tradizionale.",
    formato: "100gr *16",
    price: 9.20,
    stock: 14,
    status: "ACTIVE",
    slug: "burrata-olive-maggiorana",
    categoryName: "Burrata",
  },
  {
    name: "Burrata di Bufala",
    ProductCode: "0212000047",
    description: "Burrata di latte di bufala campana, cremosità superiore e sapore più intenso. Eccellenza casearia del Sud Italia.",
    formato: "125Gr *12",
    price: 11.80,
    stock: 16,
    status: "ACTIVE",
    slug: "burrata-di-bufala",
    categoryName: "Burrata",
  },

  // MOZZARELLA BUFALA CATEGORY (12 products)
  {
    name: "Mozzarela Di Bufala",
    ProductCode: "0212000035",
    description: "Mozzarella di bufala campana DOP, dal sapore intenso e consistenza elastica. Prodotta con latte di bufala 100% campano.",
    formato: "5*100 Gr",
    price: 12.50,
    stock: 25,
    status: "ACTIVE",
    slug: "mozzarela-di-bufala-5x100",
    categoryName: "Mozzarella Bufala",
  },
  {
    name: "Bocconcino Di Bufala",
    ProductCode: "0212000033",
    description: "Bocconcini di mozzarella di bufala campana DOP, formato pratico per insalate e antipasti. Freschezza e qualità garantite.",
    formato: "2*125 Gr",
    price: 8.90,
    stock: 32,
    status: "ACTIVE",
    slug: "bocconcino-di-bufala",
    categoryName: "Mozzarella Bufala",
  },
  {
    name: "Ciliegina",
    ProductCode: "0212000048",
    description: "Ciliegine di mozzarella di bufala DOP, formato mini perfetto per aperitivi e insalate caprese. Dolcezza e freschezza campana.",
    formato: "15Gr (250Gr*10)",
    price: 6.80,
    stock: 40,
    status: "ACTIVE",
    slug: "ciliegina-bufala",
    categoryName: "Mozzarella Bufala",
  },
  {
    name: "Mozzarella Di Bufala Campana D.O.P.",
    ProductCode: "0212000034",
    description: "Mozzarella di bufala campana DOP certificata, ciliegine in busta. Tradizione casearia campana dal 1800, sapore autentico.",
    formato: "15Gr *bolsa 250Gr",
    price: 7.20,
    stock: 35,
    status: "ACTIVE",
    slug: "mozzarella-bufala-campana-dop-ciliegine",
    categoryName: "Mozzarella Bufala",
  },
  {
    name: "Mozzarella di Bufala Campana D.O.P. 125gr",
    ProductCode: "0212000024",
    description: "Mozzarella di bufala campana DOP formato classico, prodotta nelle province di Caserta e Salerno secondo disciplinare tradizionale.",
    formato: "125gr * 12",
    price: 9.50,
    stock: 28,
    status: "ACTIVE",
    slug: "mozzarella-bufala-campana-dop-125gr",
    categoryName: "Mozzarella Bufala",
  },
  {
    name: "Mozzarella di Bufala Campana D.O.P. 250gr",
    ProductCode: "0212000031",
    description: "Mozzarella di bufala campana DOP grande formato, ideale per famiglie. Cremosità e sapore intenso della tradizione campana.",
    formato: "250gr *12",
    price: 14.80,
    stock: 20,
    status: "ACTIVE",
    slug: "mozzarella-bufala-campana-dop-250gr",
    categoryName: "Mozzarella Bufala",
  },
  {
    name: "Mozzarella di Bufala D.O.P. Treccia 1kg",
    ProductCode: "0212000053",
    description: "Treccia di mozzarella di bufala DOP da 1kg, formato professionale per ristoranti. Lavorazione artigianale a mano.",
    formato: "1 Kg",
    price: 18.90,
    stock: 15,
    status: "ACTIVE",
    slug: "mozzarella-bufala-dop-treccia-1kg",
    categoryName: "Mozzarella Bufala",
  },
  {
    name: "Mozzarella di Bufala D.O.P. Ahumada",
    ProductCode: "0212000028",
    description: "Mozzarella di bufala DOP affumicata con legni naturali, sapore unico che unisce tradizione campana e tecnica affumicatura.",
    formato: "250gr *12",
    price: 16.20,
    stock: 12,
    status: "ACTIVE",
    slug: "mozzarella-bufala-dop-ahumada",
    categoryName: "Mozzarella Bufala",
  },
  {
    name: "Mozzarella di Bufala D.O.P. Treccia 2kg",
    ProductCode: "0212000049",
    description: "Treccia di mozzarella di bufala DOP da 2kg, formato per grandi eventi e ristorazione. Lavorazione completamente manuale.",
    formato: "2 Kg",
    price: 35.50,
    stock: 8,
    status: "ACTIVE",
    slug: "mozzarella-bufala-dop-treccia-2kg",
    categoryName: "Mozzarella Bufala",
  },
  {
    name: "Mozzarella Bufala S/Lactose",
    ProductCode: "0212000036",
    description: "Mozzarella di bufala senza lattosio, per intolleranti che non vogliono rinunciare al sapore autentico della bufala campana.",
    formato: "2*125 Gr",
    price: 10.80,
    stock: 18,
    status: "ACTIVE",
    slug: "mozzarella-bufala-s-lactose",
    categoryName: "Mozzarella Bufala",
  },
  {
    name: "Mozzarella Bufala S/Lactose 500gr",
    ProductCode: "P-MBSL-PROV",
    description: "Mozzarella di bufala senza lattosio formato grande, innovazione per intolleranti. Mantiene tutto il sapore della tradizione campana.",
    formato: "500 Gr",
    price: 16.50,
    stock: 10,
    status: "ACTIVE",
    slug: "mozzarella-bufala-s-lactose-500gr",
    categoryName: "Mozzarella Bufala",
  },
  {
    name: "Bocconcino Di Bufala S/Lactose",
    ProductCode: "0212000037",
    description: "Bocconcini di mozzarella di bufala senza lattosio, formato pratico per chi ha intolleranze ma ama i sapori autentici.",
    formato: "5*50 Gr",
    price: 9.20,
    stock: 22,
    status: "ACTIVE",
    slug: "bocconcino-bufala-s-lactose",
    categoryName: "Mozzarella Bufala",
  },

  // FIOR DI LATTE CATEGORY (9 products)
  {
    name: "Fiordilatte Taglio Napoli",
    ProductCode: "0212000025",
    description: "Fior di latte taglio Napoli, mozzarella di latte vaccino della tradizione napoletana. Perfetta per pizza e piatti tipici campani.",
    formato: "6*500Gr",
    price: 8.50,
    stock: 30,
    status: "ACTIVE",
    slug: "fiordilatte-taglio-napoli",
    categoryName: "Fior di Latte",
  },
  {
    name: "Fiordilatte Julienne Taglio Fiammifero",
    ProductCode: "0212000026",
    description: "Fior di latte taglio julienne a fiammifero, formato professionale per pizzerie e ristoranti. Fusione perfetta e veloce.",
    formato: "3 Kg",
    price: 12.80,
    stock: 20,
    status: "ACTIVE",
    slug: "fiordilatte-julienne-taglio-fiammifero",
    categoryName: "Fior di Latte",
  },
  {
    name: "Fior di Latte Boccone",
    ProductCode: "0212000045",
    description: "Fior di latte a bocconi, formato professionale per ristorazione. Mozzarella di latte vaccino dalla consistenza perfetta.",
    formato: "3 Kg",
    price: 11.90,
    stock: 25,
    status: "ACTIVE",
    slug: "fior-di-latte-boccone",
    categoryName: "Fior di Latte",
  },
  {
    name: "Fior di Latte Cubettata",
    ProductCode: "0212000051",
    description: "Fior di latte cubettata, taglio uniforme per preparazioni professionali. Ideale per insalate e piatti freddi.",
    formato: "3 Kg",
    price: 12.20,
    stock: 18,
    status: "ACTIVE",
    slug: "fior-di-latte-cubettata",
    categoryName: "Fior di Latte",
  },
  {
    name: "Mozzarella Fior di Latte",
    ProductCode: "0212000032",
    description: "Mozzarella fior di latte formato famiglia, dalla tradizione casearia campana. Sapore delicato e consistenza elastica.",
    formato: "15*200 Gr",
    price: 6.80,
    stock: 35,
    status: "ACTIVE",
    slug: "mozzarella-fior-di-latte",
    categoryName: "Fior di Latte",
  },
  {
    name: "Mozzarella Fiordilatte 500gr",
    ProductCode: "0212000027",
    description: "Mozzarella fiordilatte formato medio, perfetta per uso domestico. Prodotta con latte fresco italiano di alta qualità.",
    formato: "500 Gr *6",
    price: 5.90,
    stock: 42,
    status: "ACTIVE",
    slug: "mozzarella-fiordilatte-500gr",
    categoryName: "Fior di Latte",
  },
  {
    name: "Fior di Latte 125gr",
    ProductCode: "0212000042",
    description: "Fior di latte formato piccolo, ideale per porzioni individuali. Freschezza e qualità della tradizione casearia italiana.",
    formato: "125Gr *20",
    price: 4.50,
    stock: 50,
    status: "ACTIVE",
    slug: "fior-di-latte-125gr",
    categoryName: "Fior di Latte",
  },
  {
    name: "Mozzarella Julienne",
    ProductCode: "0219000003",
    description: "Mozzarella julienne professionale, taglio sottile per fusione rapida. Formato ristorante per preparazioni veloci.",
    formato: "2 Kg",
    price: 9.80,
    stock: 28,
    status: "ACTIVE",
    slug: "mozzarella-julienne",
    categoryName: "Fior di Latte",
  },
  {
    name: "Mozzarella FDL Barra",
    ProductCode: "0212000050",
    description: "Mozzarella fior di latte a barra, formato pratico per taglio personalizzato. Ideale per pizzerie e ristoranti.",
    formato: "1 Kg",
    price: 7.20,
    stock: 32,
    status: "ACTIVE",
    slug: "mozzarella-fdl-barra",
    categoryName: "Fior di Latte",
  },

  // OTROS FRESCOS CATEGORY (18 products)
  {
    name: "Stracciatella Artigianale",
    ProductCode: "0212000021",
    description: "Stracciatella artigianale pugliese, il cuore cremoso della burrata. Prodotta a mano secondo tradizione con panna fresca.",
    formato: "250gr *10",
    price: 8.90,
    stock: 25,
    status: "ACTIVE",
    slug: "stracciatella-artigianale",
    categoryName: "Otros frescos",
  },
  {
    name: "Stracciatella Artigianale 1kg",
    ProductCode: "0217000024",
    description: "Stracciatella artigianale formato professionale, per ristoranti e pizzerie. Cremosità e sapore della tradizione pugliese.",
    formato: "1 Kg *2",
    price: 15.80,
    stock: 15,
    status: "ACTIVE",
    slug: "stracciatella-artigianale-1kg",
    categoryName: "Otros frescos",
  },
  {
    name: "Stracciatella Ahumada en Vaso",
    ProductCode: "0217000030",
    description: "Stracciatella affumicata in vaso, innovazione della tradizione pugliese. Sapore affumicato delicato e cremosità intatta.",
    formato: "250Gr *10",
    price: 10.50,
    stock: 18,
    status: "ACTIVE",
    slug: "stracciatella-ahumada-en-vaso",
    categoryName: "Otros frescos",
  },
  {
    name: "Ricotta",
    ProductCode: "1002037075",
    description: "Ricotta fresca italiana, prodotta con siero di latte di alta qualità. Sapore dolce e consistenza cremosa, tradizione casearia.",
    formato: "1,5 Kg *2",
    price: 6.50,
    stock: 30,
    status: "ACTIVE",
    slug: "ricotta-1-5kg",
    categoryName: "Otros frescos",
  },
  {
    name: "Ricotta 250gr",
    ProductCode: "1002020376",
    description: "Ricotta fresca formato famiglia, perfetta per dolci e preparazioni salate. Prodotta giornalmente con latte italiano.",
    formato: "250gr *8",
    price: 3.80,
    stock: 45,
    status: "ACTIVE",
    slug: "ricotta-250gr",
    categoryName: "Otros frescos",
  },
  {
    name: "Ricotta de Bufala",
    ProductCode: "0217000037",
    description: "Ricotta di bufala campana, sapore più intenso e cremosità superiore. Prodotta con siero di latte di bufala DOP.",
    formato: "200 Gr *12",
    price: 8.90,
    stock: 20,
    status: "ACTIVE",
    slug: "ricotta-de-bufala-200gr",
    categoryName: "Otros frescos",
  },
  {
    name: "Ricotta de Bufala 400gr",
    ProductCode: "0217000038",
    description: "Ricotta di bufala formato grande, eccellenza casearia campana. Ideale per preparazioni dolci e salate di alta qualità.",
    formato: "400 Gr *6",
    price: 12.50,
    stock: 15,
    status: "ACTIVE",
    slug: "ricotta-de-bufala-400gr",
    categoryName: "Otros frescos",
  },
  {
    name: "Mascarpone",
    ProductCode: "1002037074",
    description: "Mascarpone lombardo tradizionale, cremoso e delicato. Perfetto per tiramisù e preparazioni dolci della tradizione italiana.",
    formato: "500 gr *6",
    price: 7.80,
    stock: 25,
    status: "ACTIVE",
    slug: "mascarpone-500gr",
    categoryName: "Otros frescos",
  },
  {
    name: "Mascarpone 2kg",
    ProductCode: "0217000026",
    description: "Mascarpone formato professionale per pasticcerie e ristoranti. Cremosità e qualità lombarda per preparazioni di alto livello.",
    formato: "2 Kg *6",
    price: 22.50,
    stock: 12,
    status: "ACTIVE",
    slug: "mascarpone-2kg",
    categoryName: "Otros frescos",
  },
  {
    name: "Scamorza Ahumada Spizzico",
    ProductCode: "0217000043",
    description: "Scamorza affumicata a spicchi, formato aperitivo. Sapore affumicato delicato della tradizione casearia del Sud Italia.",
    formato: "30 Gr (250Gr *10)",
    price: 6.20,
    stock: 35,
    status: "ACTIVE",
    slug: "scamorza-ahumada-spizzico",
    categoryName: "Otros frescos",
  },
  {
    name: "Taleggio DOP",
    ProductCode: "1002037073",
    description: "Taleggio DOP lombardo, formaggio a pasta molle dalla crosta lavata. Sapore intenso e cremosità tipica delle valli bergamasche.",
    formato: "+/-2Kg",
    price: 24.80,
    stock: 8,
    status: "ACTIVE",
    slug: "taleggio-dop",
    categoryName: "Otros frescos",
  },
  {
    name: "Gorgonzola Dolce",
    ProductCode: "0217000031",
    description: "Gorgonzola dolce lombardo, erborinato cremoso dal sapore delicato. Tradizione casearia della pianura padana dal 1800.",
    formato: "1,5 Kg +/-",
    price: 18.90,
    stock: 12,
    status: "ACTIVE",
    slug: "gorgonzola-dolce",
    categoryName: "Otros frescos",
  },
  {
    name: "Iogurt de Bufala",
    ProductCode: "0320000001",
    description: "Yogurt di bufala campana, cremoso e ricco di proteine. Prodotto con latte di bufala fresco delle migliori aziende campane.",
    formato: "150 Gr *6",
    price: 5.80,
    stock: 30,
    status: "ACTIVE",
    slug: "iogurt-de-bufala",
    categoryName: "Otros frescos",
  },
  {
    name: "Mantequilla Bufala",
    ProductCode: "0227000021",
    description: "Burro di bufala campana, sapore intenso e cremosità superiore. Prodotto con panna di bufala, eccellenza casearia italiana.",
    formato: "125 Gr *40",
    price: 4.50,
    stock: 40,
    status: "ACTIVE",
    slug: "mantequilla-bufala",
    categoryName: "Otros frescos",
  },
  {
    name: "Panna Cotta de Bufala",
    ProductCode: "0221000003",
    description: "Panna cotta di bufala, dolce tradizionale piemontese con latte di bufala campana. Cremosità e sapore unici.",
    formato: "100 Gr",
    price: 3.80,
    stock: 25,
    status: "ACTIVE",
    slug: "panna-cotta-de-bufala",
    categoryName: "Otros frescos",
  },
  {
    name: "Kefir de Bufala",
    ProductCode: "P-KEFB-PROV",
    description: "Kefir di bufala, bevanda fermentata probiotica. Innovazione salutistica con latte di bufala campana, ricco di fermenti vivi.",
    formato: "200 Gr *6",
    price: 6.80,
    stock: 18,
    status: "ACTIVE",
    slug: "kefir-de-bufala",
    categoryName: "Otros frescos",
  },
  {
    name: "Queso fresco de Bufala para untar",
    ProductCode: "P-QFRE-PROV",
    description: "Formaggio fresco di bufala spalmabile, cremoso e delicato. Perfetto per aperitivi e colazioni, innovazione della tradizione campana.",
    formato: "150 Gr *6",
    price: 7.20,
    stock: 22,
    status: "ACTIVE",
    slug: "queso-fresco-bufala-untar",
    categoryName: "Otros frescos",
  },
  {
    name: "Perlas de Bufala envueltas de crema fresca",
    ProductCode: "P-PBCF-PROV",
    description: "Perle di bufala avvolte in crema fresca, specialità gourmet. Piccole sfere di mozzarella di bufala in crema, esperienza unica.",
    formato: "500 Gr",
    price: 14.50,
    stock: 10,
    status: "ACTIVE",
    slug: "perlas-bufala-crema-fresca",
    categoryName: "Otros frescos",
  },

  // CURADOS CATEGORY (9 products)
  {
    name: "Gran Moravia",
    ProductCode: "0217000005",
    description: "Gran Moravia, formaggio stagionato ceco di alta qualità. Sapore intenso e consistenza compatta, perfetto per grattugie e degustazioni.",
    formato: "500 Gr *10",
    price: 12.80,
    stock: 20,
    status: "ACTIVE",
    slug: "gran-moravia-500gr",
    categoryName: "Curados",
  },
  {
    name: "Gran Moravia Rallado",
    ProductCode: "1002037090",
    description: "Gran Moravia grattugiato, pronto all'uso per pasta e risotti. Stagionatura prolungata per sapore intenso e aroma persistente.",
    formato: "1 Kg",
    price: 15.50,
    stock: 25,
    status: "ACTIVE",
    slug: "gran-moravia-rallado",
    categoryName: "Curados",
  },
  {
    name: "Gran Moravia En Laminas",
    ProductCode: "0201020522",
    description: "Gran Moravia a lamelle, taglio professionale per antipasti e piatti gourmet. Presentazione elegante e sapore intenso.",
    formato: "1 Kg",
    price: 16.80,
    stock: 15,
    status: "ACTIVE",
    slug: "gran-moravia-laminas",
    categoryName: "Curados",
  },
  {
    name: "Gran Moravia 1/8",
    ProductCode: "0217000003",
    description: "Gran Moravia in ottavo di forma, formato tradizionale per taglio personalizzato. Stagionatura minima 12 mesi.",
    formato: "4 Kg +/-",
    price: 45.00,
    stock: 8,
    status: "ACTIVE",
    slug: "gran-moravia-1-8",
    categoryName: "Curados",
  },
  {
    name: "Parmigiano Reggiano D.O.P. Gran Fiore",
    ProductCode: "0202020436",
    description: "Parmigiano Reggiano DOP Gran Fiore, stagionato 24 mesi. Re dei formaggi italiani dalle province di Parma, Reggio Emilia e Modena.",
    formato: "1 Kg +/-",
    price: 28.50,
    stock: 15,
    status: "ACTIVE",
    slug: "parmigiano-reggiano-dop-gran-fiore",
    categoryName: "Curados",
  },
  {
    name: "Parmigiano Reggiano Rueda Entera",
    ProductCode: "0202020582",
    description: "Parmigiano Reggiano DOP ruota intera, stagionato 24+ mesi. Eccellenza assoluta della tradizione casearia emiliana, formato professionale.",
    formato: "34 Kg +/-",
    price: 850.00,
    stock: 2,
    status: "ACTIVE",
    slug: "parmigiano-reggiano-rueda-entera",
    categoryName: "Curados",
  },
  {
    name: "Queso Fontal",
    ProductCode: "1002037066",
    description: "Formaggio Fontal, pasta semi-dura dal sapore dolce e delicato. Tradizione casearia alpina, perfetto per fondute e piatti gratinati.",
    formato: "2 Kg +/-",
    price: 16.80,
    stock: 12,
    status: "ACTIVE",
    slug: "queso-fontal",
    categoryName: "Curados",
  },
  {
    name: "Scamorza Ahumada",
    ProductCode: "1002037060",
    description: "Scamorza affumicata stagionata, dalla caratteristica forma a pera. Affumicatura naturale con legni aromatici del Sud Italia.",
    formato: "2,5 Kg +/-",
    price: 22.50,
    stock: 10,
    status: "ACTIVE",
    slug: "scamorza-ahumada-stagionata",
    categoryName: "Curados",
  },
  {
    name: "Provolone Dolce",
    ProductCode: "0217000002",
    description: "Provolone dolce stagionato, formaggio a pasta filata della tradizione del Sud Italia. Sapore delicato e consistenza compatta.",
    formato: "5,6 Kg +/-",
    price: 38.90,
    stock: 6,
    status: "ACTIVE",
    slug: "provolone-dolce",
    categoryName: "Curados",
  },
];
