services:
  # 🗄️ DATABASE - PostgreSQL
  postgres:
    image: postgres:latest
    container_name: shop_db
    restart: always
    environment:
      - POSTGRES_USER=shopmefy
      - POSTGRES_PASSWORD=shopmefy
      - POSTGRES_DB=shopmefy
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shopme_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopmefy"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shopme_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
