services:
  # 🗄️ DATABASE - PostgreSQL
  postgres:
    image: postgres:latest
    container_name: shop_db
    restart: always
    environment:
      - POSTGRES_USER=shopmefy
      - POSTGRES_PASSWORD=shopmefy
      - POSTGRES_DB=shopmefy
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shopme_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopmefy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🚀 N8N - Workflow Automation Platform (Unified Configuration)
  n8n:
    image: n8nio/n8n:latest
    container_name: shopme_n8n_unified
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # 🔐 Authentication Settings
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Venezia44
      
      # 🌐 Network Settings  
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      
      # 🔑 API Keys & Secrets
      - OPENROUTER_API_KEY=sk-or-v1-78c47a3d3e2b2a0faf8b7e9c5d4b6a1e8f9c2d1a5b6e9f0c3a7b8d2e5f1c4a9b6
      - SHOPME_API_URL=http://host.docker.internal:3001
      - INTERNAL_API_SECRET=internal_api_secret_n8n_shopme_2024
      - FRONTEND_URL=http://localhost:3000
      
      # 🗄️ Database Settings
      - N8N_DATABASE_TYPE=sqlite
      - N8N_DATABASE_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
      
      # 🎛️ UI & UX Settings
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_ONBOARDING_FLOW_DISABLED=true
      - N8N_HIRING_BANNER_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_POSTHOG_DISABLED=true
      - N8N_ANONYMIZE_DATA_COLLECTION=true
      
      # 🔒 Security Settings
      - N8N_USER_MANAGEMENT_DISABLED=false
      - N8N_USER_MANAGEMENT_JWT_SECRET=shopme-jwt-secret-key-12345
      - N8N_ENCRYPTION_KEY=shopme-encryption-key-12345678901234567890
      
      # 📧 Email Settings
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=localhost
      - N8N_SMTP_PORT=587
      - N8N_SMTP_USER=admin
      - N8N_SMTP_PASS=Venezia44
      - N8N_SMTP_SENDER=admin@shopme.com
      
      # 🌍 Localization
      - N8N_DEFAULT_LOCALE=en
      - GENERIC_TIMEZONE=Europe/Rome
    volumes:
      - ./.n8n:/home/node/.n8n
      - ./n8n/workflows:/import-workflows:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shopme_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shopme_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
